-- MySQL Script generated by MySQL Workbench
-- Wed Jul 19 03:44:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema limbikani
-- -----------------------------------------------------
--  

-- -----------------------------------------------------
-- Schema limbikani
--
--  
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `limbikani` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `limbikani` ;

-- -----------------------------------------------------
-- Table `limbikani`.`orgProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `limbikani`.`orgProfile` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `phoneNumber08` VARCHAR(45) NULL,
  `phoneNumber09` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `HQ` VARCHAR(45) NULL,
  `vision` LONGTEXT NULL,
  `mission` LONGTEXT NULL,
  `logo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `limbikani`.`programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `limbikani`.`programs` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `limbikani`.`partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `limbikani`.`partners` (
  `id` INT NOT NULL,
  `logo` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `limbikani`.`portfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `limbikani`.`portfolio` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `images` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `limbikani`.`orgAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `limbikani`.`orgAdmin` (
  `id` INT NOT NULL,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `limbikani`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `limbikani`.`donation` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `program` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `limbikani`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `limbikani`.`feedback` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `content` LONGTEXT NULL,
  `email` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
